languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "Jakub Żojdzik"
# copyright = "Copy, _right?_ :thinking_face:"

[params]
  dateFormat = "2 January 2006"
  mainSections = ["posts"]
  description = "My personal portfolio website "

[params.author]
  name = "Jakub Żojdzik"
  # image = "img/author.jpg"
  headline = "I write coffee to drink code"
  links = [
     { email = "mailto:jakubzojdzik@duck.com" },
     { github = "https://github.com/JakubZojdzik" },
   ]
